name: macOS Build

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch: [x86_64, arm64]
        include:
          - arch: x86_64
            cflags: -O3 -arch x86_64
            cxxflags: -O3 -arch x86_64
            ldflags: -arch x86_64
          - arch: arm64
            cflags: -O3 -arch arm64
            cxxflags: -O3 -arch arm64
            ldflags: -arch arm64
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Meson and Ninja
      run: |
        pip install meson ninja

    - name: Configure with Meson
      run: |
        meson setup build -Denable_zip=true -Denable_http=false -Dbuild_static=true -Dzstd:lz4=disabled -Dzstd:zlib=disabled -Dzstd:lzma=disabled -Dwrap_mode=forcefallback --buildtype=release --optimization=3
      env:
        CFLAGS: ${{ matrix.cflags }}
        CXXFLAGS: ${{ matrix.cxxflags }}
        LDFLAGS: ${{ matrix.ldflags }} -Wl,-dead_strip

    - name: Build with Ninja
      run: |
        ninja -C build

    - name: Verify architecture
      run: |
        strip build/payload-dumper-ungo
        file build/payload-dumper-ungo
        lipo -info build/payload-dumper-ungo

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: payload-dumper-ungo-macos-${{ matrix.arch }}
        path: build/payload-dumper-ungo
        if-no-files-found: error
